### ISSUE TITLE
Already existing documentation

### ISSUE THREAD

**Issue by Zwolf8** [Zwolf8/Zwolf8.github.io#3]
![2018-07-03_09-25-01](https://user-images.githubusercontent.com/22533350/42232256-b010cf6e-7ea2-11e8-90cf-590d27d76fb9.png)

I already gave you docs for profile begin and end and keypress and keyrelease are already documentated in the api so is unlockmodulescript

SecureFunction(SecureFunction) Loads a Secure Function (Ive seen 3ds do it before...) So yea you can document that

**Comment by Alexflamer11** [comment]
Secure function is the last changed that needs to be made before this issue is closed.
