### ISSUE TITLE
Fix hooking api documentation redirect

### ISSUE THREAD

**Issue by Zwolf8** [Zwolf8/Zwolf8.github.io#5]
This redirects to the old site the old thread doesnt exist on the new site

![2018-07-03_09-35-15](https://user-images.githubusercontent.com/22533350/42232699-1a4bcf86-7ea4-11e8-8051-1d4a692e77ed.png)

make it redirect to the one on v3rmillion https://v3rmillion.net/showthread.php?tid=524553

**Comment by Alexflamer11** [comment]
Link has been redirected.
